#!/usr/bin/env swift

import Foundation

// Simple script to check stuck files status
print("🔍 FTP Downloader - Stuck Files Checker")
print("========================================")

// This script will help diagnose what's happening with the 5 stuck files
print("")
print("Based on the code analysis, here are the possible stuck states:")
print("")
print("1. 🔄 .stabilizing - Files waiting to be stabilized (size not stable yet)")
print("   - Check if stabilization process is running")
print("   - Check if file sizes are changing")
print("   - Check stabilization interval settings")
print("")
print("2. ✅ .stabilized - Files marked as stabilized but not being picked up")
print("   - Check if download process is running")
print("   - Check if download slots are available")
print("   - Check maxConcurrentDownloads setting")
print("")
print("3. 📥 .downloading - Files stuck in download process")
print("   - Check if FTP connection is healthy")
print("   - Check if download tasks are active")
print("   - Check for network timeouts")
print("")
print("4. ❌ .failed - Files that failed and need retry")
print("   - Check retry count vs maxRetries")
print("   - Check error messages in logs")
print("   - Check if retry mechanism is working")
print("")
print("🔧 To diagnose the issue:")
print("")
print("1. Use showAllFileStatuses(config:) to see current status")
print("2. Use forceResetStuckFiles(config:) to reset stuck files")
print("3. Check if the 3-process architecture is working:")
print("   - Discovery process (every sync interval)")
print("   - Stabilization process (every 1 second)")
print("   - Download process (every 1 second)")
print("")
print("4. Check timer status:")
print("   - syncTimers")
print("   - stabilizationTimers") 
print("   - downloadTimers")
print("")
print("5. Check process flags:")
print("   - scanningRunning")
print("   - stabilizationRunning")
print("   - readyDownloadProcessing")
print("")
print("The most likely issue is that one of the 3 processes is not running")
print("or there's a deadlock between them.")
